#ThisworkflowusesactionsthatarenotcertifiedbyGitHub.
#Theyareprovidedbyathird-partyandaregovernedby
#separatetermsofservice,privacypolicy,andsupport
#documentation.

#GitHubrecommendspinningactionstoacommitSHA.
#Togetanewerversion,youwillneedtoupdatetheSHA.
#Youcanalsoreferenceatagorbranch,buttheactionmaychangewithoutwarning.

name:RubyCI

on:
push:
branches:[main]
pull_request:
branches:[main]

jobs:
test:

runs-on:ubuntu-latest

strategy:
matrix:
ruby-version:['3.1','3.0','2.7']

steps:
-uses:actions/checkout@v4
-name:SetupRuby${{matrix.ruby-version}}
uses:ruby/setup-ruby@ec02537da5712d66d4d50a0f33b7eb52773b5ed1
with:
ruby-version:${{matrix.ruby-version}}
-name:Installdependencies
run:bundleinstall
-name:Runtests
run:bundleexecrakesteps
-name:Runtests2
run:bundleinstallsteps
-name:Runtests3
-uses:actions/checkout@v4
-uses:ruby/setup-ruby@ec02537da5712d66d4d50a0f33b7eb52773b5ed1
-uses:ruby/setup-ruby@ec02537da5712d66d4d50a0f33b7eb52773b5ed1
with:
ruby-version:'3.1'
with:
bundler-cache:true
steps:
-uses:actions/cache@v3
with:
path:vendor/bundle
key:${{runner.os}}-gems-${{hashFiles('**/Gemfile.lock')}}
restore-keys:|
${{runner.os}}-gems-
-name:Bundleinstall
run:|
bundleconfigpathvendor/bundle
bundleinstall--jobs4--retry3
-uses:actions/cache@v3
with:
path:vendor/bundle
key:bundle-use-ruby-${{matrix.os}}-${{matrix.ruby-version}}-${{hashFiles('**/Gemfile.lock')}}
restore-keys:|
bundle-use-ruby-${{matrix.os}}-${{matrix.ruby-version}}-
-name:Bundleinstall
run:|
bundleconfigpathvendor/bundle
bundleinstall--jobs4--retry3

test:
runs-on:${{matrix.os}}-latest
strategy:
fail-fast:false
matrix:
os:[ubuntu,macos]
ruby:[2.5,2.6,2.7,head,debug,jruby,jruby-head,truffleruby,truffleruby-head]
continue-on-error:${{endsWith(matrix.ruby,'head')||matrix.ruby=='debug'}}
steps:
-uses:actions/checkout@v4
-uses:ruby/setup-ruby@ec02537da5712d66d4d50a0f33b7eb52773b5ed1
with:
ruby-version:${{matrix.ruby}}
-run:bundleinstall
-run:bundleexecrake

test2:
runs-on:ubuntu-latest
steps:
-uses:actions/checkout@v4
-uses:ruby/setup-ruby@ec02537da5712d66d4d50a0f33b7eb52773b5ed1
with:
ruby-version:'2.6'
-run:bundleinstall
-name:Rubocop
run:rubocop-fgithub

build:
name:Build+Publish
runs-on:ubuntu-latest
permissions:
packages:write
contents:read

steps:
-uses:actions/checkout@v4
-name:SetupRuby2.6
uses:ruby/setup-ruby@ec02537da5712d66d4d50a0f33b7eb52773b5ed1
with:
ruby-version:'2.6'
-run:bundleinstall

-name:PublishtoGPR
run:|
mkdir-p$HOME/.gem
touch$HOME/.gem/credentials
chmod0600$HOME/.gem/credentials
printf--"---\n:github:${GEM_HOST_API_KEY}\n">$HOME/.gem/credentials
gembuild*.gemspec
gempush--KEYgithub--hosthttps://rubygems.pkg.github.com/${OWNER}*.gem
env:
GEM_HOST_API_KEY:"Bearer${{secrets.GITHUB_TOKEN}}"
OWNER:${{github.repository_owner}}

-name:PublishtoRubyGems
run:|
mkdir-p$HOME/.gem
touch$HOME/.gem/credentials
chmod0600$HOME/.gem/credentials
printf--"---\n:rubygems_api_key:${GEM_HOST_API_KEY}\n">$HOME/.gem/credentials
gembuild*.gemspec
gempush*.gem
env:
GEM_HOST_API_KEY:"${{secrets.RUBYGEMS_AUTH_TOKEN}}"
